// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ActivityMonitorML.Model
{
    public class ModelInput
    {
        [ColumnName("R"), LoadColumn(0)]
        public float R { get; set; }


        [ColumnName("1"), LoadColumn(1)]
        public float Col1 { get; set; }


        [ColumnName("2"), LoadColumn(2)]
        public float Col2 { get; set; }


        [ColumnName("3"), LoadColumn(3)]
        public float Col3 { get; set; }


        [ColumnName("4"), LoadColumn(4)]
        public float Col4 { get; set; }


        [ColumnName("5"), LoadColumn(5)]
        public float Col5 { get; set; }


        [ColumnName("6"), LoadColumn(6)]
        public float Col6 { get; set; }


        [ColumnName("7"), LoadColumn(7)]
        public float Col7 { get; set; }


        [ColumnName("8"), LoadColumn(8)]
        public float Col8 { get; set; }


        [ColumnName("9"), LoadColumn(9)]
        public float Col9 { get; set; }


        [ColumnName("10"), LoadColumn(10)]
        public float Col10 { get; set; }


        [ColumnName("11"), LoadColumn(11)]
        public float Col11 { get; set; }


        [ColumnName("12"), LoadColumn(12)]
        public float Col12 { get; set; }


        [ColumnName("13"), LoadColumn(13)]
        public float Col13 { get; set; }


        [ColumnName("14"), LoadColumn(14)]
        public float Col14 { get; set; }


        [ColumnName("15"), LoadColumn(15)]
        public float Col15 { get; set; }


        [ColumnName("16"), LoadColumn(16)]
        public float Col16 { get; set; }


        [ColumnName("17"), LoadColumn(17)]
        public float Col17 { get; set; }


        [ColumnName("18"), LoadColumn(18)]
        public float Col18 { get; set; }


        [ColumnName("19"), LoadColumn(19)]
        public float Col19 { get; set; }


        [ColumnName("20"), LoadColumn(20)]
        public float Col20 { get; set; }


        [ColumnName("21"), LoadColumn(21)]
        public float Col21 { get; set; }


        [ColumnName("22"), LoadColumn(22)]
        public float Col22 { get; set; }


        [ColumnName("23"), LoadColumn(23)]
        public float Col23 { get; set; }


        [ColumnName("24"), LoadColumn(24)]
        public float Col24 { get; set; }


        [ColumnName("25"), LoadColumn(25)]
        public float Col25 { get; set; }


        [ColumnName("26"), LoadColumn(26)]
        public float Col26 { get; set; }


        [ColumnName("27"), LoadColumn(27)]
        public float Col27 { get; set; }


        [ColumnName("28"), LoadColumn(28)]
        public float Col28 { get; set; }


        [ColumnName("29"), LoadColumn(29)]
        public float Col29 { get; set; }


        [ColumnName("30"), LoadColumn(30)]
        public float Col30 { get; set; }


        [ColumnName("31"), LoadColumn(31)]
        public float Col31 { get; set; }


        [ColumnName("32"), LoadColumn(32)]
        public float Col32 { get; set; }


        [ColumnName("33"), LoadColumn(33)]
        public float Col33 { get; set; }


        [ColumnName("34"), LoadColumn(34)]
        public float Col34 { get; set; }


        [ColumnName("35"), LoadColumn(35)]
        public float Col35 { get; set; }


        [ColumnName("36"), LoadColumn(36)]
        public float Col36 { get; set; }


        [ColumnName("37"), LoadColumn(37)]
        public float Col37 { get; set; }


        [ColumnName("38"), LoadColumn(38)]
        public float Col38 { get; set; }


        [ColumnName("39"), LoadColumn(39)]
        public float Col39 { get; set; }


        [ColumnName("40"), LoadColumn(40)]
        public float Col40 { get; set; }


        [ColumnName("41"), LoadColumn(41)]
        public float Col41 { get; set; }


        [ColumnName("42"), LoadColumn(42)]
        public float Col42 { get; set; }


        [ColumnName("43"), LoadColumn(43)]
        public float Col43 { get; set; }


        [ColumnName("44"), LoadColumn(44)]
        public float Col44 { get; set; }


        [ColumnName("45"), LoadColumn(45)]
        public float Col45 { get; set; }


        [ColumnName("46"), LoadColumn(46)]
        public float Col46 { get; set; }


        [ColumnName("47"), LoadColumn(47)]
        public float Col47 { get; set; }


        [ColumnName("48"), LoadColumn(48)]
        public float Col48 { get; set; }


        [ColumnName("49"), LoadColumn(49)]
        public float Col49 { get; set; }


        [ColumnName("50"), LoadColumn(50)]
        public float Col50 { get; set; }


        [ColumnName("51"), LoadColumn(51)]
        public float Col51 { get; set; }


        [ColumnName("52"), LoadColumn(52)]
        public float Col52 { get; set; }


        [ColumnName("53"), LoadColumn(53)]
        public float Col53 { get; set; }


        [ColumnName("54"), LoadColumn(54)]
        public float Col54 { get; set; }


        [ColumnName("55"), LoadColumn(55)]
        public float Col55 { get; set; }


        [ColumnName("56"), LoadColumn(56)]
        public float Col56 { get; set; }


        [ColumnName("57"), LoadColumn(57)]
        public float Col57 { get; set; }


        [ColumnName("58"), LoadColumn(58)]
        public float Col58 { get; set; }


        [ColumnName("59"), LoadColumn(59)]
        public float Col59 { get; set; }


        [ColumnName("60"), LoadColumn(60)]
        public float Col60 { get; set; }


        [ColumnName("61"), LoadColumn(61)]
        public float Col61 { get; set; }


        [ColumnName("62"), LoadColumn(62)]
        public float Col62 { get; set; }


        [ColumnName("63"), LoadColumn(63)]
        public float Col63 { get; set; }


        [ColumnName("64"), LoadColumn(64)]
        public float Col64 { get; set; }


    }
}
